# version: 0.2

# phases:
#   install:
#     runtime-versions:
#       java: corretto8
#   pre_build:
#     commands:
#       - echo Nothing to do in the pre_build phase...
#   build:
#     commands:
#       - echo Build started on `date2`
#       - mvn install
#   post_build:
#     commands:
#       - echo Build completed on `date2`
# artifacts:
#   files:
#     - target/demo-0.0.1-SNAPSHOT.jar


version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      #- $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - mvn clean install
      - docker build -t 542272068077.dkr.ecr.us-east-1.amazonaws.com/test-ecr:lates .
      # - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      #- docker push 542272068077.dkr.ecr.us-east-1.amazonaws.com/test-ecr:lates
      # - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
