version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date2`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date2`
artifacts:
  files:
    - target/demo-0.0.1-SNAPSHOT.jar